#!/usr/bin/env bash
set -eu

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

. "$DIR/common-setup.sh"

echo "Entering the reflex sandbox..."

google-chrome file:///$(nix-build $NIXOPTS --no-out-link "$DIR" -A ghcjs.squares-client)/bin/squares-single.jsexe/index.html


nix-shell "$DIR/shell.nix" $NIXOPTS --command "echo \"$INFO\" ; return" "$@"
